---
title: "Class 12: Structural Informatics Pt II"
output: github_document
---

Load bio3d & download pdb file.
```{r}
library(bio3d)
pdb.code <- "1hsg"
file.name <- get.pdb(pdb.code)
```
Read pdb file of HIV protease + MK1 drug.
```{r}
hiv <- read.pdb(file.name)
hiv
```


Make isolated protein & ligand files for autodock.
```{r}
prot <- trim.pdb(hiv, "protein")
prot
lig <- trim.pdb(hiv, "ligand")
lig

```

Isolated protein file generation.
```{r}
prot.filename <- paste(pdb.code, "_protein.pdb", sep = "")
write.pdb(prot, file=prot.filename)
```


Isolated ligand file generation
```{r}
lig.filename <- paste(pdb.code, "_ligand.pdb", sep = "")
write.pdb(lig, file=lig.filename)
```

Play around in Autodock.

## Convert our docking results for viewing in VMD
```{r}
library(bio3d)
res <- read.pdb("all.pdbqt", multi=TRUE)
write.pdb(res, file="results.pdb")

```

```{r}
ori <- read.pdb("ligand.pdbqt")
rmsd(ori, res)
```

To view the docking of new drugs into protein. Load 1hsg.pdb into vmd then our results.pdb file.
